---
base::proxy_server: 'http://outbound.egiproxy.property.rbi.web.ds:3128'
base::octopus_server_url: 'http://10.52.63.172'
base::elasticsearch_server: 'http://elasticsearch.logging.property.rbi.web.ds/elastic/'

profile::teamcity::agent::server_url: 'http://teamcity.property.rbi.web.ds:8050'
